class Commands:
    LEECH = "leech"
    PURGE = "purge"
    PAUSEALL = "pauseall"
    RESUMEALL = "resumeall"
    STATUS = "status"
    SETTINGS = "settings"
    EXEC = "command"
    UPLOAD = "upload"
    YTDL = "ytdl"
    PYTDL = "pytdl"
    ABOUT = "about"
    GETLOGS = "log"
    SERVER = "server"
    USERSETTINGS = "usetting"